In [1]:
from Library.UtilsTools.DataGenerater import get_linear_data
from Library.UtilsTools.GradChecking.GradChecking import estimate_grad
from Library.BPLayer import Linear
import numpy as np

In [2]:
X,y = get_linear_data(size=(10,2),seed=10)
layer = Linear(2,1)

In [3]:
temp = (X,)
grad_approx, grad_cal = estimate_grad(layer,temp,temp,0.001)

In [4]:
grad_cal = grad_cal[-1]
grad_approx = grad_approx.reshape(-1)

In [5]:
grad_cal, grad_approx, grad_cal==grad_approx

(array([-0.65275032, -0.44551111, -0.23559845, -0.01634791,  0.23987245,
         0.45004582,  0.69400298,  0.91884225,  1.10553926,  1.38015732]),
 array([-0.65275032, -0.44551111, -0.23559845, -0.01634791,  0.23987245,
         0.45004582,  0.69400298,  0.91884225,  1.10553926,  1.38015732]),
 array([False, False, False, False, False, False, False, False, False,
        False]))