In [7]:
from Library.Normalize import PCA, DataNormalize
import numpy as np

In [2]:
X = np.array([[84,65,61,72,79,81],
              [64,77,77,76,55,70],
              [65,67,63,49,57,67],
              [74,80,69,75,63,74],
              [84,74,70,80,74,82],
              [84,65,61,72,79,81],
              [64,77,77,76,55,70],
              [65,67,63,49,57,67],
              [74,80,69,75,63,74],
              [84,74,70,80,74,82]])

In [3]:
pca = PCA(inn=6, out=2)

In [5]:
result = pca(X)
result

array([[-2.49079591,  1.17700221],
       [ 2.05182575, -1.45497368],
       [ 1.83161475,  2.41287609],
       [ 0.40725188, -1.06247592],
       [-1.79989646, -1.07242871],
       [-2.49079591,  1.17700221],
       [ 2.05182575, -1.45497368],
       [ 1.83161475,  2.41287609],
       [ 0.40725188, -1.06247592],
       [-1.79989646, -1.07242871]])

In [6]:
X_recreated = pca.restore(result)
X_recreated

array([[ 1.25684719, -1.13361052, -1.26021142, -0.05297672,  1.38626675,
         1.10090233],
       [-1.0060056 ,  1.21200779,  1.30882   ,  0.32153178, -1.16060786,
        -0.82615015],
       [-1.12237905, -1.04521999, -0.90162469, -1.83791044, -0.89341776,
        -1.35481619],
       [-0.15291137,  0.68395884,  0.69125681,  0.50675291, -0.26009094,
        -0.03529597],
       [ 1.02444883,  0.28286388,  0.1617593 ,  1.06260247,  0.9278498 ,
         1.11535998],
       [ 1.25684719, -1.13361052, -1.26021142, -0.05297672,  1.38626675,
         1.10090233],
       [-1.0060056 ,  1.21200779,  1.30882   ,  0.32153178, -1.16060786,
        -0.82615015],
       [-1.12237905, -1.04521999, -0.90162469, -1.83791044, -0.89341776,
        -1.35481619],
       [-0.15291137,  0.68395884,  0.69125681,  0.50675291, -0.26009094,
        -0.03529597],
       [ 1.02444883,  0.28286388,  0.1617593 ,  1.06260247,  0.9278498 ,
         1.11535998]])

In [8]:
DataNormalize()(pca.X_origin)

array([[ 1.12295566, -1.3221891 , -1.23743687,  0.14543051,  1.42327862,
         1.04859064],
       [-1.16879058,  0.7654779 ,  1.59099026,  0.50900678, -1.12587711,
        -0.81181211],
       [-1.05420327, -0.9742446 , -0.88388348, -1.94513306, -0.91344747,
        -1.31919468],
       [-0.02291746,  1.28739465,  0.1767767 ,  0.41811271, -0.27615854,
        -0.13530202],
       [ 1.12295566,  0.24356115,  0.35355339,  0.87258306,  0.89220451,
         1.21771816],
       [ 1.12295566, -1.3221891 , -1.23743687,  0.14543051,  1.42327862,
         1.04859064],
       [-1.16879058,  0.7654779 ,  1.59099026,  0.50900678, -1.12587711,
        -0.81181211],
       [-1.05420327, -0.9742446 , -0.88388348, -1.94513306, -0.91344747,
        -1.31919468],
       [-0.02291746,  1.28739465,  0.1767767 ,  0.41811271, -0.27615854,
        -0.13530202],
       [ 1.12295566,  0.24356115,  0.35355339,  0.87258306,  0.89220451,
         1.21771816]])