In [1]:
from Library.Algorithms import KMeans
from Library.UtilsTools.DataGenerater import get_picture_data

In [2]:
X_pic = get_picture_data(mode="numpy")
X = X_pic.reshape(-1,4)
X

array([[105, 117, 185, 255],
       [105, 117, 185, 255],
       [105, 117, 185, 255],
       ...,
       [ 51,  80, 104, 255],
       [ 51,  80, 104, 255],
       [ 51,  80, 104, 255]], dtype=uint8)

In [3]:
kmeans = KMeans(K=3)
centers = kmeans(X)
centers

[array([167.95494861, 181.07039134, 231.8260315 , 255.        ]),
 array([ 38.99284404,  47.15206418,  37.30659736, 255.        ]),
 array([ 82.13417659, 105.25874837, 133.54116395, 255.        ])]

In [4]:
kmeans.get_classified_data()

[array([[120, 134, 197, 255],
        [120, 134, 197, 255],
        [120, 134, 197, 255],
        ...,
        [159, 170, 193, 255],
        [159, 170, 193, 255],
        [159, 170, 193, 255]], dtype=uint8),
 array([[ 44,  45,  64, 255],
        [ 44,  45,  64, 255],
        [ 44,  45,  64, 255],
        ...,
        [ 39,  71,  98, 255],
        [ 39,  71,  98, 255],
        [ 39,  71,  98, 255]], dtype=uint8),
 array([[105, 117, 185, 255],
        [105, 117, 185, 255],
        [105, 117, 185, 255],
        ...,
        [ 51,  80, 104, 255],
        [ 51,  80, 104, 255],
        [ 51,  80, 104, 255]], dtype=uint8)]